teleop_twist_joy_node:
  ros__parameters:
    # Mapeo estándar de Xbox/Logitech (verificar con jstest si varía)
    axis_linear:
      x: 1  # Stick Izquierdo Vertical
    axis_angular:
      yaw: 3 # Stick Derecho Horizontal
      
    # Escalas de velocidad (m/s y rad/s)
    scale_linear:
      x: 0.5
    scale_angular:
      yaw: 10.0

    # Botón de seguridad (hombre muerto). 
    # 5 suele ser RB (Right Bumper). El robot no se mueve si no lo aprietas.
    enable_button: 5
    require_enable_button: true

    # --- ¡LA SOLUCIÓN A TU PROBLEMA! ---
    publish_stamped_twist: true
    frame_id: "base_link" # Necesario para TwistStamped